source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AGJointOperationSDKDemo', :exclusive => true do
  pod 'AGJointOperationSDK', :path => '../'
end

target 'AGJointOperationSDKDemoTests', :exclusive => true do
  pod 'AGJointOperationSDK', :path => '../'

  pod 'Kiwi'
end
